services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - wetrack-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allows empty root password
      MYSQL_DATABASE: wetrack
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
      - ./wetrack.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wetrack-network
    command: --default-authentication-plugin=mysql_native_password  # Allows root user with empty password

networks:
  wetrack-network:
    driver: bridge

volumes:
  mysql_data:
