version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "53:53/udp"  # Expose the DNS port
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      wetrack-network:
        aliases:
          - mywebsite.local  # Automatically resolves to the container's IP
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: wetrack
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./wetrack.sql:/docker-entrypoint-initdb.d/wetrack.sql
    ports:
      - "3306:3306"
    networks:
      - wetrack-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  wetrack-network:
    driver: bridge

volumes:
  mysql_data:
